
[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
  directory = "/.netlify/functions/server"
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/server/:splat"